# services:
#   legacy-python-app:
#     build: .
#     container_name: legacy-python-container
#     volumes:
#       - ./app:/app
#     command: python /app/app.py


# version: '3.8'

# services:
#   legacy-python-app:
#     build: .
#     container_name: legacy-python-container-app
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./app:/app
#     command: python /app/app.py
#     environment:
#       - FLASK_DEBUG=1




services:
  legacy-python-app:
    build: .
    container_name: legacy-python-container-app
    ports:
      - "5000:5000"   # Expose Flask app port
    volumes:
      - ./app:/app
    command: python /app/app.py
    environment:
      - FLASK_DEBUG=1
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Jothisree@18
      - MYSQL_DB=expense_db
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-legacy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jothisree@18
      MYSQL_DATABASE: expense_db
    ports:
      - "3307:3306"   # MySQL default port exposed
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
